### PR TITLE
CI: Fix choice

### PR DESCRIPTION
**Pull request by xiaoleGun**
Co-authored-by: セリカ・シルフィル <64072399+natsumerinchan@users.noreply.github.com>
Signed-off-by: xiaoleGun <1592501605@qq.com>

### CODE REVIEW

**Comment by xiaoleGun** [comment]
Close #4

**Comment by natsumerinchan** [comment]
We can use boolean instead of choice to solve `Invalid type found: string was expected but boolean was found`

2023-01-24 18-21-00 的屏幕截图

https://github.com/natsumerinchan/KernelSU_Oneplus_9RT_Action/commit/a11a30ba7152bab1bc5906e5fbd4ec11d620b25d

**Comment by xiaoleGun** [comment]
Oh, what i have encountered is the problem caused by my own modification of variable name. also we can use boolean instead of string, please you PR.

**Comment by xiaoleGun** [comment]
and remember change config.env

**Comment by natsumerinchan** [comment]
Ok,I will do it after dinner.

**Pull request merged**
