### PR TITLE
CI: Support apply KernelSU patch

### PR DESCRIPTION
**Pull request by bdqllW**
If kprobe does not work in your kernel (may be an upstream or kernel bug below 4.8), then you can try this way
from: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#manually-modify-the-kernel-source

README: Update

### CODE REVIEW

**Comment by xiaoleGun** [comment]
A suggestion, perhaps we can use grep and sed to add more commonality than patch?

**Comment by bdqllW** [comment]
> A suggestion, perhaps we can use grep and sed to add more commonality than patch?

Well, I'll try

**Comment by xiaoleGun** [comment]
you not must to be close this PR, you can also use force push

**Comment by xiaoleGun** [comment]
https://github.com/xiaoleGun/KernelSU_Action/commit/5b5b266f39e8ca19f10d331597827ff544d2941c

check it

**Comment by bdqllW** [comment]
> [5b5b266](https://github.com/xiaoleGun/KernelSU_Action/commit/5b5b266f39e8ca19f10d331597827ff544d2941c)
> 
> check it

Great script, provides better compatibility

**Pull request merged**
